version: "3.9"
services:
  hugo:
    image: klakegg/hugo:0.79.1-ext-alpine
    # command: server -e production
    volumes:
        - $PWD:/src   
        - $PWD/docs:/target  
    ports:
      - "1313:1313"
    environment: 
     - HUGO_PANDOC=pandoc_command
     - HUGO_ENV=production