name: Hugo site CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Hugo Build
      uses: klakegg/actions-hugo@1.0.0
      with:
        env: production
    - name: Updating docs
      uses: actions-x/commit@v2
      with:
        message: Updating docs       
