name: Hugo site CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Hugo Build
      uses: klakegg/actions-hugo@1.0.0
      with:
        env: production
        version: 0.79.1
        image: ext-alpine
        target: docs
    - name: Updating docs
      uses: actions-x/commit@v2
      with:
        message: Updating docs       
